### ISSUE TITLE
Workflows that have an explicit name that differs from the trait name can't be called using a typed stub

### ISSUE THREAD

**Issue by oridag** [vitaliihonta/zio-temporal#57]
When giving the workflow an explicit name (with `workflowMethod` annotation) that is different from the trait name, the workflow is not found when using a typed stub.
I assume this is due to the move to untyped stubs internally

**Comment by vitaliihonta** [comment]
@oridag should be fixed in 0.2.0-M6. Could you confirm it?

**Comment by oridag** [comment]
Yep, looks good 👍 
I still have at leas one more issue, I'll report when I narrow it down
